#takes a directory full of barcode depth files generated by samtools depth, labels which amplicon each position refers to, and concatenates into a single depth file 
import os 
import pandas as pd

DEPTH_DIR='/global/scratch/users/chandlersutherland/nanopore/20211109_CS/S3/20211109_1827_MN35019_AIH759_d0d0cd8b/depth'
AMPLICONS='/global/scratch/users/chandlersutherland/nanopore/amplicons.bed'
amp_position = pd.read_csv(AMPLICONS, sep='\t', header=0, names=['Chromosome', 'start', 'end', 'marker', 'code'], index_col=False)

col_names=['Chromosome', 'Position', 'depth', 'Marker', 'Barcode']
depth_file = pd.DataFrame(columns=col_names)
os.chdir(DEPTH_DIR)
for FILE in os.listdir(DEPTH_DIR):
    basename = os.path.basename(FILE)
    barcode = basename.split(".")[0]
    print(barcode)
    depth=pd.read_csv(FILE, sep='\t', header=None, names=['Chromosome', 'Position', 'depth'], index_col=False)
    depth['Marker']=''
    print(depth)
    
    for j in range(0, len(depth)): 
        for i in range(0, len(amp_position)): 
            if depth.iloc[j, 0] == amp_position.iloc[i, 0]:
                if amp_position.iloc[i, 1] <= depth.iloc[j, 1] <= amp_position.iloc[i, 2]:
                    depth.iloc[j, 3] = amp_position.iloc[i, 3]
    
    depth['Barcode']= barcode
    depth_file = pd.concat([depth_file, depth], ignore_index=True)
    len(depth_file)

depth_file.to_csv(DEPTH_DIR+'/concatenated_depth.tsv', sep='\t', index=False)